import Link from "next/link";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { dateTime } from "@/lib/utils";
import { StatusBadge } from "@/components/status-badge";
import { LiveRefresh } from "@/components/live-refresh";

type Period = "all"|"today"|"yesterday"|"7d"|"30d"|"month"|"lastMonth"|"custom";
function range(period:Period, from?:string, to?:string) { const now=new Date(); const start=new Date(); const end=new Date(); if(period==="all")return undefined; if(period==="today")start.setHours(0,0,0,0); if(period==="yesterday"){start.setDate(now.getDate()-1);start.setHours(0,0,0,0);end.setDate(now.getDate()-1);end.setHours(23,59,59,999);} if(period==="7d")start.setDate(now.getDate()-6),start.setHours(0,0,0,0); if(period==="30d")start.setDate(now.getDate()-29),start.setHours(0,0,0,0); if(period==="month")start.setDate(1),start.setHours(0,0,0,0); if(period==="lastMonth"){start.setMonth(now.getMonth()-1,1);start.setHours(0,0,0,0);end.setDate(0);end.setHours(23,59,59,999);} if(period==="custom"&&from){start.setTime(new Date(`${from}T00:00:00`).getTime());if(to)end.setTime(new Date(`${to}T23:59:59.999`).getTime());} return period==="custom"&&!from?undefined:{gte:start,lte:end}; }
const statusWhere:Record<string,Prisma.AccessLinkWhereInput>={ pending:{status:{in:["REQUESTED","GENERATED"]}}, opened:{status:"ACCESSED"}, converted:{status:"CONVERTED"}, expired:{status:{in:["EXPIRED","REVOKED"]}} };

export default async function LinksPage({searchParams}:{searchParams:Promise<{period?:Period;from?:string;to?:string;status?:string}>}){const {period="today",from,to,status="all"}=await searchParams;const requestedAt=range(period,from,to);const links=await prisma.accessLink.findMany({where:{...(requestedAt?{requestedAt}:{}),...(statusWhere[status]??{})},include:{customer:true,order:{include:{items:{include:{product:true}}}},upsells:true},orderBy:{requestedAt:"desc"},take:200});const totals={pending:links.filter(l=>["REQUESTED","GENERATED"].includes(l.status)).length,opened:links.filter(l=>l.status==="ACCESSED").length,converted:links.filter(l=>l.status==="CONVERTED").length};return <div className="space-y-6"><LiveRefresh/>
<div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#87f0bf]">Entrega · Telegram · upsell</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Links e conversão</h1><p className="mt-1 text-sm muted">Acompanhe o link enviado, a abertura e a compra de upsell sem sair do painel.</p></div><span className="text-xs text-[#9aa4b4]">Atualização automática a cada 10 s</span></div>
<section className="panel p-3"><div className="flex flex-wrap items-center gap-2"><span className="mr-1 text-xs font-bold uppercase tracking-wider muted">Período</span>{([['all','Tudo'],['today','Hoje'],['yesterday','Ontem'],['7d','7 dias'],['30d','30 dias'],['month','Este mês'],['lastMonth','Mês passado']] as const).map(([key,label])=><Link key={key} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold transition ${period===key?"bg-[#87f0bf] text-[#082017] shadow-sm":"bg-[#1a202a] text-[#b5bdca] hover:bg-[#222936]"}`} href={`/links?period=${key}&status=${status}`}>{label}</Link>)}<form action="/links" className="ml-auto flex flex-wrap items-center gap-2"><input type="hidden" name="period" value="custom"/><input type="hidden" name="status" value={status}/><span className="text-xs muted">Personalizado</span><input aria-label="Data inicial" className="input h-9 w-auto text-sm" name="from" type="date" defaultValue={from}/><span className="muted">—</span><input aria-label="Data final" className="input h-9 w-auto text-sm" name="to" type="date" defaultValue={to}/><button className="btn btn-secondary h-9 px-3 text-sm">Ver</button></form></div></section>
<div className="grid gap-3 sm:grid-cols-3"><Link href={`/links?period=${period}&status=pending`} className="panel p-4 hover:border-[#3b4657]"><p className="text-sm muted">Não abertos / aguardando</p><p className="mt-2 text-2xl font-bold">{totals.pending}</p></Link><Link href={`/links?period=${period}&status=opened`} className="panel p-4 hover:border-[#3b4657]"><p className="text-sm muted">Abriu, sem compra ainda</p><p className="mt-2 text-2xl font-bold">{totals.opened}</p></Link><Link href={`/links?period=${period}&status=converted`} className="panel p-4 hover:border-[#87f0bf]"><p className="text-sm muted">Compras aprovadas</p><p className="mt-2 text-2xl font-bold text-[#87f0bf]">{totals.converted}</p></Link></div>
<div className="panel table-wrap"><table><thead><tr><th>Cliente</th><th>Produto / pedido</th><th>Link</th><th>Situação</th><th>Enviado</th><th>Aberto</th><th>Compra</th></tr></thead><tbody>{links.map(l=><tr key={l.id}><td className="font-semibold">{l.customer.name}<span className="block text-xs muted">{l.customer.email}</span></td><td>{l.order.items[0]?.product.name??"—"}<span className="block text-xs muted">{l.order.externalOrderId}</span></td><td>{l.url?<a className="inline-block max-w-48 truncate text-[#87f0bf] hover:underline" href={l.url} target="_blank" rel="noreferrer">Abrir link</a>:"Aguardando N8N"}</td><td><StatusBadge status={l.status}/></td><td>{dateTime(l.generatedAt??l.requestedAt)}</td><td>{dateTime(l.lastAccessedAt)}</td><td>{l.status==="CONVERTED"?"Aprovada":l.status==="ACCESSED"?"Ainda não":l.status==="EXPIRED"||l.status==="REVOKED"?"Não aprovada":"Aguardando"}</td></tr>)}{!links.length&&<tr><td colSpan={7} className="py-12 text-center muted">Nenhum link para este filtro.</td></tr>}</tbody></table></div></div>}
