import { prisma } from "@/lib/prisma";
import { money, dateTime } from "@/lib/utils";
import { StatusBadge } from "@/components/status-badge";
import { DollarSign, ShoppingBag, RefreshCw, Link2, AlertCircle, Clock } from "lucide-react";
import Link from "next/link";

function startOfDay() { const d = new Date(); d.setHours(0,0,0,0); return d; }
export default async function DashboardPage() { const today = startOfDay(); const [paid, active, renewals, refused, pending, links, recent] = await Promise.all([
  prisma.order.aggregate({ where:{ status:"PAID", approvedAt:{ gte: today } }, _sum:{ amountCents:true }, _count:true }),
  prisma.subscription.count({ where:{ status:"ACTIVE" } }),
  prisma.subscription.findMany({ where:{ lastRenewedAt:{ gte:today } }, include:{ customer:true }, orderBy:{lastRenewedAt:"desc"}, take:8 }),
  prisma.order.count({ where:{ status:"REFUSED", createdAt:{gte:today} } }),
  prisma.order.count({ where:{ status:"PENDING" } }),
  prisma.accessLink.groupBy({ by:["status"], _count:true }),
  prisma.webhookInbox.findMany({ orderBy:{createdAt:"desc"},take:12 })
 ]);
 const generated = links.filter(x=>["GENERATED","ACCESSED","CONVERTED"].includes(x.status)).reduce((a,x)=>a+x._count,0); const requested=links.find(x=>x.status==="REQUESTED")?._count ?? 0;
 const kpis = [{label:"Faturamento hoje",value:money(paid._sum.amountCents ?? 0),icon:DollarSign},{label:"Vendas aprovadas",value:String(paid._count),icon:ShoppingBag},{label:"Ticket médio",value:money(paid._count ? Math.round((paid._sum.amountCents ?? 0)/paid._count):0),icon:DollarSign},{label:"Assinaturas ativas",value:String(active),icon:RefreshCw},{label:"Renovações hoje",value:String(renewals.length),icon:RefreshCw,highlight:true},{label:"Recusas hoje",value:String(refused),icon:AlertCircle},{label:"Pendências",value:String(pending),icon:Clock},{label:"Links prontos / N8N",value:`${generated} / ${requested}`,icon:Link2}];
 return <div className="space-y-7"><div><p className="text-sm text-[#87f0bf]">Operações</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Visão geral</h1><p className="mt-1 text-sm text-[#9099aa]">Indicadores do dia e atividade recebida pelos webhooks.</p></div><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(({label,value,icon:Icon,highlight})=><div key={label} className={`panel p-4 ${highlight ? "border-[#87f0bf]/60 bg-[#10261d]" : ""}`}><div className="flex items-start justify-between"><p className="text-sm text-[#9ea8b9]">{label}</p><Icon size={17} className={highlight?"text-[#87f0bf]":"text-[#68768c]"}/></div><p className="mt-3 text-2xl font-bold">{value}</p></div>)}</section><section className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><div className="panel"><div className="flex items-center justify-between border-b border-[#252a35] px-5 py-4"><div><h2 className="font-bold">Renovações de hoje</h2><p className="text-sm text-[#9099aa]">{renewals.length} renovadas hoje</p></div><Link href="/assinaturas?tab=Renovadas" className="text-sm font-semibold text-[#87f0bf]">Ver assinaturas</Link></div><div className="divide-y divide-[#202530]">{renewals.length ? renewals.map(s=><Link href={`/assinaturas/${s.id}`} key={s.id} className="flex items-center justify-between px-5 py-4 hover:bg-[#161b23]"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#1e4132] font-bold text-[#87f0bf]">{s.customer.name.slice(0,2).toUpperCase()}</span><div><p className="font-medium">{s.customer.name}</p><p className="text-xs text-[#9099aa]">{s.planName ?? "Assinatura"} · {dateTime(s.lastRenewedAt)}</p></div></div><div className="flex items-center gap-2"><span className="badge badge-green">NOVA</span><StatusBadge status={s.status}/></div></Link>):<p className="p-8 text-center text-sm text-[#9099aa]">Nenhuma renovação recebida hoje.</p>}</div></div><div className="panel"><div className="border-b border-[#252a35] px-5 py-4"><h2 className="font-bold">Feed ao vivo</h2><p className="text-sm text-[#9099aa]">Últimos eventos</p></div><div className="divide-y divide-[#202530]">{recent.length ? recent.map(e=><div key={e.id} className="px-5 py-3"><div className="flex justify-between gap-4"><p className="text-sm font-medium">{e.eventType.replaceAll("_"," ")}</p><span className="text-xs text-[#9099aa]">{dateTime(e.createdAt)}</span></div><p className="mt-1 text-xs text-[#9099aa]">{e.source}</p></div>):<p className="p-8 text-center text-sm text-[#9099aa]">Aguardando o primeiro webhook.</p>}</div></div></section></div>; }
